#!/usr/bin/env python3
"""Significance of the free-flight feedforward improvement.

For each take-off metric, pairs the per-cell means (one cell = one
case-controller condition) without and with the feedforward and
reports the exact one-sided sign-test p-value together with the
one-sided Wilcoxon signed-rank p-value. Simulation cells come from
docs/ff_sim_summary.csv (22 cells); hardware cells from the per-trial
CSV of analysis/freeflight_metrics.py (10 cells, both feedforward
variants). Emits docs/tab_ff_significance.tex.

Usage
-----
  python analysis/ff_significance.py <freeflight_metrics_runs.csv>
                                     [--outdir DIR]
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy.stats import binomtest, wilcoxon

KEYS = ('tilt', 'rate', 'drift', 'speed')
NAME = {'tilt': 'peak tilt', 'rate': 'peak body rate',
        'drift': 'translational drift', 'speed': 'peak speed'}


def cells(rows, ctrl_key, var):
    """(case, controller) -> mean metric values of one variant."""
    acc = defaultdict(lambda: defaultdict(list))
    for r in rows:
        if r['variant'] != var:
            continue
        for k in KEYS:
            acc[(r['case'], r[ctrl_key])][k].append(float(r[k]))
    return {c: {k: float(np.mean(v)) for k, v in d.items()}
            for c, d in acc.items()}


def tests(base, comp):
    """Per metric: n, improved count, sign-test p, Wilcoxon p."""
    out = {}
    for k in KEYS:
        d = np.array([base[c][k] - comp[c][k] for c in sorted(base)])
        n, imp = len(d), int((d > 0).sum())
        p_sign = binomtest(imp, n, 0.5, alternative='greater').pvalue
        p_wil = wilcoxon(d, alternative='greater').pvalue
        out[k] = (n, imp, p_sign, p_wil)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('hw_csv', type=Path,
                    help='freeflight_metrics_runs.csv written by '
                         'analysis/freeflight_metrics.py')
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    sim = list(csv.DictReader(open(args.outdir / 'ff_sim_summary.csv')))
    hw = list(csv.DictReader(open(args.hw_csv)))

    blocks = [('Simulation', tests(
        {c: d for c, d in cells(sim, 'controller', 'wo_ff').items()},
        cells(sim, 'controller', 'w_ff')))]
    for var, lab in (('ff_pivot_based', 'pivot-based'),
                     ('ff_pivot_free', 'pivot-free')):
        blocks.append((f'Hardware, {lab}', tests(
            cells(hw, 'controller', 'wo_ff'),
            cells(hw, 'controller', var))))

    def pfmt(p):
        return f'$<10^{{{int(np.ceil(np.log10(p)))}}}$' if p < 1e-3 \
            else f'${p:.3f}$'

    out = args.outdir / 'tab_ff_significance.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Sign-test and Wilcoxon significance of the free-flight\n'
            '% feedforward improvement, per metric, on paired\n'
            '% case-controller cell means.  Generated by\n'
            '% analysis/ff_significance.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Significance of the feedforward improvement:\n'
            'cells improved out of the paired case--controller cells,\n'
            'with the exact one-sided sign-test and Wilcoxon\n'
            'signed-rank $p$-values.}\n'
            '\\label{tab:ff_significance}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}llccc@{}}\n\\toprule\n'
            'Campaign & metric & improved & sign test & Wilcoxon\\\\\n'
            '\\midrule\n')
        for lab, res in blocks:
            for i, k in enumerate(KEYS):
                n, imp, ps, pw = res[k]
                lead = lab if i == 0 else ''
                fh.write(f'{lead} & {NAME[k]} & {imp}/{n} & '
                         f'{pfmt(ps)} & {pfmt(pw)}\\\\\n')
                print(f'{lab:22s} {NAME[k]:20s} {imp}/{n}  '
                      f'sign p={ps:.2e}  wilcoxon p={pw:.2e}')
            fh.write('\\addlinespace\n')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
