#!/usr/bin/env python3
"""Campaign-level aggregate of the simulated free-flight metrics.

Collapses the per-case table (tab_ff_sim.tex) into one row per take-off
metric: for each controller and variant, the mean over the 11 offset
configurations and the empirical 95% interval (2.5--97.5 percentiles of
the per-case means, three flights each). Reads docs/ff_sim_summary.csv
written by analysis/freeflight_sim_summary.py.

Usage
-----
  python analysis/ff_sim_aggregate.py [--outdir DIR]
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

KEYS = ('tilt', 'rate', 'drift', 'speed')
ROW = {'tilt': ('peak tilt', '[deg]', 1.0, 1),
       'rate': ('peak body rate', '[deg/s]', 1.0, 0),
       'drift': ('translational drift', '[cm]', 100.0, 1),
       'speed': ('peak horizontal speed', '[m/s]', 1.0, 2)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    vals = defaultdict(list)        # (ctrl, variant, key) -> per-case means
    with open(args.outdir / 'ff_sim_summary.csv') as fh:
        for r in csv.DictReader(fh):
            for k in KEYS:
                vals[(r['controller'], r['variant'], k)].append(
                    float(r[k]))

    ctrls = sorted({c for c, _, _ in vals})

    def cell(ctrl, var, k):
        _, _, scale, dp = ROW[k]
        v = scale * np.array(vals[(ctrl, var, k)])
        lo, hi = np.percentile(v, [2.5, 97.5])
        return (f'${v.mean():.{dp}f}$ $[{lo:.{dp}f},\\,{hi:.{dp}f}]$')

    out = args.outdir / 'tab_ff_sim_agg.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Campaign-level aggregate of the simulated free-flight\n'
            '% take-off metrics: mean and empirical 95% interval over\n'
            '% the 11 offset configurations (per-case means, three\n'
            '% flights each).  Generated by analysis/ff_sim_aggregate.py.\n'
            '\\begin{tabular}{@{}l cc cc@{}}\n\\toprule\n'
            f' & \\multicolumn{{2}}{{c}}{{{ctrls[0]}}} & '
            f'\\multicolumn{{2}}{{c}}{{{ctrls[1]}}}\\\\\n'
            '\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n'
            'metric & w/o FF & w/ FF & w/o FF & w/ FF\\\\\n'
            '\\midrule\n')
        for k in KEYS:
            name, unit, _, _ = ROW[k]
            cells = ' & '.join(cell(c, v, k) for c in ctrls
                               for v in ('wo_ff', 'w_ff'))
            fh.write(f'{name} {unit} & {cells}\\\\\n')
        fh.write('\\bottomrule\n\\end{tabular}\n')
    print(f'written to {out}')
    for k in KEYS:
        name, unit, _, _ = ROW[k]
        print(f'{name:22s} ' + '  '.join(
            f'{c}/{v}: {cell(c, v, k)}'
            for c in ctrls for v in ('wo_ff', 'w_ff')))


if __name__ == '__main__':
    main()
