#!/usr/bin/env python3
"""Campaign-level aggregate of the simulated free-flight metrics.

Collapses the per-case table (tab_ff_sim.tex) into one row per take-off
metric and controller: the median over the 11 offset configurations and
the empirical 95% interval (2.5--97.5 percentiles of the per-case
means, three flights each), for the uncompensated and compensated
variants, plus the per-case improvement percentage
100 (uncomp - comp)/uncomp aggregated the same way. Reads
docs/ff_sim_summary.csv written by analysis/freeflight_sim_summary.py.

Usage
-----
  python analysis/ff_sim_aggregate.py [--outdir DIR]
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

KEYS = ('tilt', 'rate', 'drift', 'speed')
ROW = {'tilt': ('$\\vartheta_{\\mathrm{peak}}$ [deg]', 1.0, 1),
       'rate': ('$\\omega_{\\mathrm{peak}}$ [deg/s]', 1.0, 0),
       'drift': ('$p_{\\mathrm{peak}}$ [m]', 1.0, 3),
       'speed': ('$v_{\\mathrm{peak}}$ [m/s]', 1.0, 2)}
HEAD = {'HGDO': 'HGDO', 'L1': '$\\mathcal{L}_1$'}


def stat(v, dp):
    med = np.median(v)
    lo, hi = np.percentile(v, [2.5, 97.5])
    return f'${med:.{dp}f}$ $[{lo:.{dp}f},\\,{hi:.{dp}f}]$'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    vals = defaultdict(dict)        # (ctrl, key) -> {variant: case -> mean}
    with open(args.outdir / 'ff_sim_summary.csv') as fh:
        for r in csv.DictReader(fh):
            for k in KEYS:
                vals[(r['controller'], k)].setdefault(
                    r['variant'], {})[r['case']] = float(r[k])

    ctrls = sorted({c for c, _ in vals})
    out = args.outdir / 'tab_ff_sim_agg.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Campaign-level aggregate of the simulated free-flight\n'
            '% take-off metrics: median and empirical 95% interval over\n'
            '% the 11 offset configurations (per-case means, three\n'
            '% flights each); improvement is the per-case percentage\n'
            '% 100 (uncomp - comp)/uncomp aggregated the same way.\n'
            '% Generated by analysis/ff_sim_aggregate.py.\n'
            '\\begin{tabular}{@{}l ccc@{}}\n\\toprule\n'
            'metric & Uncomp & Comp & improvement [\\%]\\\\\n'
            '\\midrule\n')
        for ci, ctrl in enumerate(ctrls):
            if ci:
                fh.write('\\addlinespace\n')
            fh.write(f'\\multicolumn{{4}}{{@{{}}l}}'
                     f'{{\\textbf{{{HEAD.get(ctrl, ctrl)}}}}}\\\\\n')
            for k in KEYS:
                name, scale, dp = ROW[k]
                wo = vals[(ctrl, k)]['wo_ff']
                w_ = vals[(ctrl, k)]['w_ff']
                cases = sorted(wo)
                a = scale * np.array([wo[c] for c in cases])
                b = scale * np.array([w_[c] for c in cases])
                imp = 100.0 * (a - b) / a
                fh.write(f'{name} & {stat(a, dp)} & {stat(b, dp)} & '
                         f'{stat(imp, 0)}\\\\\n')
                print(f'{ctrl:5s} {k:6s} uncomp {stat(a, dp)}  '
                      f'comp {stat(b, dp)}  imp {stat(imp, 0)}')
        fh.write('\\bottomrule\n\\end{tabular}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
