#!/usr/bin/env python3
"""Audit of the simulated excitation runs against the run gates.

Recomputes, for every R3 excitation run, exactly the three quantities
the onset-free gates of extract_piecewise_batch evaluate -- the
realized window sample count N_full, the ramp-rate error epsilon of
the floor-masked slope, and the linearity RMSE about the window's own
best-fit line -- and emits a checklist table of the runs that fail
any of them (docs/tab_sim_gate_exclusions.tex), failing entries in
bold.

Usage
-----
  PYTHONPATH=<stubs> python analysis/gate_audit.py [--outdir DIR]
"""
import argparse
import contextlib
import io
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'analysis'))
import critical_value_getter_piecewise as cvp         # noqa: E402
from utils.extractor import load_packed_dataset       # noqa: E402

CASES = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9',
         'S11', 'S13']
N_MIN, EPS_MAX, LIN_MAX = 38, 3.0, 0.030


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows, tot = [], 0
    for case in CASES:
        for simax, axis in (('Mx', 'x'), ('My', 'y')):
            with contextlib.redirect_stdout(io.StringIO()):
                bags = load_packed_dataset(f'SimDataSet/R3/{case}/{simax}')
            for bag in bags:
                cmd = cvp.commanded_ramp_rate(bag.name)
                if cmd is None:
                    continue
                tot += 1
                with contextlib.redirect_stdout(io.StringIO()):
                    sig = cvp.prepare_signals(bag, axis)
                i0, i1 = cvp.detect_excitation_window(
                    sig['moment'], moment_cap=cvp.MOMENT_CAP.get(axis))
                n_full = i1 - i0 + 1
                t_w = sig['t'][i0:i1 + 1]
                m_w = sig['moment'][i0:i1 + 1]
                a, b = np.polyfit(t_w, m_w, 1)
                lin = float(np.std(m_w - (a * t_w + b)))
                floor = cvp.SLOPE_GATE_FLOOR.get(axis, 0.0)
                mask = np.abs(m_w) >= floor
                a_g = (np.polyfit(t_w[mask], m_w[mask], 1)[0]
                       if int(mask.sum()) >= 10 else a)
                eps = (abs(float(a_g)) - cmd) / cmd * 100.0
                if (n_full < N_MIN or abs(eps) > EPS_MAX
                        or lin > LIN_MAX):
                    rows.append((case, simax, bag.name, cmd, n_full,
                                 eps, 1e3 * lin))

    rows.sort(key=lambda r: (CASES.index(r[0]), r[1], r[3], r[2]))
    out = args.outdir / 'tab_sim_gate_exclusions.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Checklist of the simulated excitation runs excluded by\n'
            '% the onset-free run gates: the three gate quantities per\n'
            '% run, failing entries in bold.  Generated by\n'
            '% analysis/gate_audit.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Simulated excitation runs excluded by the run\n'
            f'gates ({len(rows)} of {tot}; gates: '
            f'$N_{{\\mathrm{{full}}}} \\ge {N_MIN}$, '
            f'$|\\epsilon| \\le {EPS_MAX:.0f}\\%$, linearity RMSE '
            f'$\\le {1e3 * LIN_MAX:.0f}$\\,mN$\\cdot$m).}}\n'
            '\\label{tab:sim_gate_exclusions}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}llcccc@{}}\n'
            '\\toprule\n'
            'Case & Run & $\\dot M$ & $N_{\\mathrm{full}}$ & '
            '$\\epsilon$ [\\%] & lin.\\ RMSE [mN$\\cdot$m]\\\\\n'
            '\\midrule\n')
        for case, simax, name, cmd, n_full, eps, lin in rows:
            direc = 'neg' if name.startswith('neg') else 'pos'
            nf = (f'\\textbf{{{n_full}}}' if n_full < N_MIN
                  else f'{n_full}')
            ef = (f'\\textbf{{{eps:+.1f}}}' if abs(eps) > EPS_MAX
                  else f'{eps:+.1f}')
            lf = (f'\\textbf{{{lin:.0f}}}' if lin > 1e3 * LIN_MAX
                  else f'{lin:.0f}')
            fh.write(f'{case}/{simax} & {direc} & {cmd:g} & {nf} & '
                     f'{ef} & {lf}\\\\\n')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'{len(rows)}/{tot} excluded; written to {out}')


if __name__ == '__main__':
    main()
