#!/usr/bin/env python3
"""How close the benchmark detectors sit to the deployed COSH readout.

Per gated hardware run, the paired difference of the detected
critical moment against COSH on the same run,

    Delta = sgn (M_method - M_COSH)   [mN.m],

with sgn = +1 on positive and -1 on negative tips so that
Delta > 0 uniformly means the method detects later (larger
magnitude) than COSH. Emits per-method median and empirical 95%
interval over the campaign (docs/tab_mcrit_method_diff.tex).

Usage
-----
  python analysis/mcrit_method_diff.py <scratch>/nls_comparison_runs.csv
                                       [--outdir DIR]
"""
import argparse
import csv
from pathlib import Path

import numpy as np

METHODS = [('cosh_cad', 'COSH-CAD'), ('nls', 'PNLS'),
           ('pelt_normal', 'CPD-N'), ('pelt_rbf', 'CPD-R'),
           ('cusum', 'CUSUM')]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('csv', type=Path)
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows = list(csv.DictReader(open(args.csv)))
    out = args.outdir / 'tab_mcrit_method_diff.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Paired per-run difference of each benchmark detector\n'
            '% against the deployed COSH readout, direction-corrected\n'
            '% (positive = detects later than COSH).  Generated by\n'
            '% analysis/mcrit_method_diff.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Detected critical moment of each benchmark\n'
            'against the deployed COSH readout on the same run:\n'
            'direction-corrected paired difference\n'
            '$\\Delta = \\mathrm{sgn}\\,(M_{\\mathrm{method}} -\n'
            'M_{\\mathrm{COSH}})$ over the 140 gated hardware runs\n'
            '(positive: later detection than COSH).}\n'
            '\\label{tab:mcrit_method_diff}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}lccc@{}}\n\\toprule\n'
            ' & \\multicolumn{3}{c}{$\\Delta$ [mN$\\cdot$m]}\\\\\n'
            '\\cmidrule(l){2-4}\n'
            'method & median & 95\\% interval & median $|\\Delta|$\\\\\n'
            '\\midrule\n')
        for key, lab in METHODS:
            d = np.array([
                (1.0 if r['dir'] == 'pos' else -1.0)
                * 1e3 * (float(r[f'mcrit_{key}']) - float(r['mcrit_cosh']))
                for r in rows if r.get(f'mcrit_{key}')])
            lo, hi = np.percentile(d, [2.5, 97.5])
            fh.write(f'{lab} & ${np.median(d):+.0f}$ & '
                     f'$[{lo:+.0f},\\,{hi:+.0f}]$ & '
                     f'${np.median(np.abs(d)):.0f}$\\\\\n')
            print(f'{lab:9s} n={len(d):3d} median {np.median(d):+6.1f} '
                  f'[{lo:+7.1f},{hi:+7.1f}]  med|d| '
                  f'{np.median(np.abs(d)):6.1f} mN·m')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
