#!/usr/bin/env python3
"""Theoretical critical moments with and without the ground effect.

Reads mcrit_prediction.csv (written by analysis/mcrit_prediction.py)
and emits a table of the static thresholds of (7)/(14) per case, axis
and tip direction under the three ground-effect treatments the
static-threshold figure draws: none, single rotor, and the
parameter-free rotor-interference model. Two parallel blocks (Mx
left, My right).

Usage
-----
  python analysis/mcrit_theory_table.py <scratch> [--outdir DIR]
"""
import argparse
import csv
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scratch', help='directory holding '
                                    'mcrit_prediction.csv')
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    pred = {(r['case'], r['axis'], r['dir']): r
            for r in csv.DictReader(
                open(Path(args.scratch) / 'mcrit_prediction.csv'))}
    cases = sorted({k[0] for k in pred})

    def cell(case, axis, dirn):
        r = pred[(case, axis, dirn)]
        c = case.replace('case_0', '')
        sgn = '$-$' if dirn == 'neg' else '$+$'
        return (f'{c}/{sgn} & ${float(r["M_ident"]):+.3f}$ & '
                f'${float(r["M_pred"]):+.3f}$ '
                f'$({float(r["resid_mNm"]):+.0f})$ & '
                f'${float(r["M_pred_single"]):+.3f}$ '
                f'$({float(r["resid_single_mNm"]):+.0f})$ & '
                f'${float(r["M_pred_interf"]):+.3f}$ '
                f'$({float(r["resid_interf_mNm"]):+.0f})$')

    out = args.outdir / 'tab_mcrit_ge.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Theoretical critical moments of (7)/(14) under the\n'
            '% three ground-effect treatments, per case, axis and tip\n'
            '% direction (measured onset collective and odometry-\n'
            '% fitted contact arm of each group).  Generated by\n'
            '% analysis/mcrit_theory_table.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Identified critical moments '
            '$M_{\\mathrm{crit,est}}$ (COSH group mean) against the '
            'theoretical thresholds [N$\\cdot$m] with and without the '
            'ground effect: none, the single-rotor model, and the '
            'parameter-free rotor-interference model. Parentheses: '
            'deviation of the identified moment from that threshold, '
            '$M_{\\mathrm{crit,est}} - M_{\\mathrm{crit,th}}$ '
            '[mN$\\cdot$m].}\n'
            '\\label{tab:mcrit_ge}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}lcccc@{\\qquad}lcccc@{}}\n'
            '\\toprule\n'
            '\\multicolumn{5}{c}{$M_{x}$} & '
            '\\multicolumn{5}{c}{$M_{y}$}\\\\\n'
            '\\cmidrule(r){1-5}\\cmidrule(l){6-10}\n'
            'Case & $M_{\\mathrm{crit,est}}$ & none & single & '
            'interf. & '
            'Case & $M_{\\mathrm{crit,est}}$ & none & single & '
            'interf.\\\\\n'
            '\\midrule\n')
        for case in cases:
            for dirn in ('neg', 'pos'):
                fh.write(f'{cell(case, "Mx", dirn)} & '
                         f'{cell(case, "My", dirn)}\\\\\n')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
