#!/usr/bin/env python3
"""Per-case static critical-moment residual of the reported readout,
under the rotor-interference ground-effect model, as a table.

Same aggregation as the per-case panel of
analysis/mcrit_residual_boxplot.py: per case and axis the directional
medians with their within-case IQRs, the antisymmetric half
0.5(med_pos - med_neg) the ground-effect term acts on, and the
pivot-free combination M_ff = 0.5(med_pos + med_neg) that carries the
direction-symmetric case offset.  The block footer gives the spread of
the five case medians against the median within-case IQR -- the
case-level-offset vs run-level-noise contrast the manuscript cites.

Usage
-----
  python analysis/mcrit_prediction.py <outdir>          # writes the CSV
  python analysis/mcrit_residual_case_table.py <outdir>/mcrit_per_run.csv
                                               [--outdir DIR]
"""
import argparse
import csv
from pathlib import Path

import numpy as np

COL = 'resid_interf_mNm'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('csv', type=Path, help='mcrit_per_run.csv written '
                                           'by analysis/mcrit_prediction.py')
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows = list(csv.DictReader(open(args.csv)))
    cases = sorted({r['case'] for r in rows})

    def take(axn, dirn, case=None):
        return np.array([float(r[COL]) for r in rows
                         if r['axis'] == axn and r['dir'] == dirn
                         and (case is None or r['case'] == case)])

    def iqr(v):
        return float(np.subtract(*np.percentile(v, [75, 25])))

    out = args.outdir / 'tab_mcrit_residual_case.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Per-case static critical-moment residual under the\n'
            '% rotor-interference ground-effect model.\n'
            '% Generated by analysis/mcrit_residual_case_table.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Per-case residual\n'
            '$M_{\\mathrm{crit,est}} - M_{\\mathrm{crit,th}}$ [mN$\\cdot$m]\n'
            'under the rotor-interference ground-effect model: directional\n'
            'medians with within-case IQRs, the antisymmetric half\n'
            '$\\Delta_a = \\tfrac12(\\mathrm{med}_+ - \\mathrm{med}_-)$,\n'
            'and the symmetric half\n'
            '$\\Delta_s = \\tfrac12(\\mathrm{med}_+ + \\mathrm{med}_-)$\n'
            '(the part the pivot-free average carries). Each block closes\n'
            'with the spread of the five case medians against the median\n'
            'within-case IQR.}\n'
            '\\label{tab:mcrit_residual_case}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}lcccc@{}}\n'
            '\\toprule\n'
            'Case & med$_+$ (IQR) & med$_-$ (IQR) & $\\Delta_a$'
            ' & $\\Delta_s$\\\\\n')
        for axn in ('Mx', 'My'):
            fh.write('\\midrule\n'
                     f'\\multicolumn{{5}}{{@{{}}l}}{{$M_{axn[1]}$}}\\\\\n'
                     '\\addlinespace[1pt]\n')
            print(f'{axn:4} {"case":8}{"med+":>8}{"IQR+":>7}{"med-":>8}'
                  f'{"IQR-":>7}{"antisym":>9}{"M_ff":>7}')
            for j, case in enumerate(cases):
                vp, vn = take(axn, 'pos', case), take(axn, 'neg', case)
                mp, mn = np.median(vp), np.median(vn)
                anti, mff = 0.5 * (mp - mn), 0.5 * (mp + mn)
                fh.write(f'E{j + 1} & ${mp:+.0f}$ (${iqr(vp):.0f}$) & '
                         f'${mn:+.0f}$ (${iqr(vn):.0f}$) & '
                         f'${anti:+.0f}$ & ${mff:+.0f}$\\\\\n')
                print(f'     {case:8}{mp:8.1f}{iqr(vp):7.1f}{mn:8.1f}'
                      f'{iqr(vn):7.1f}{anti:9.1f}{mff:7.1f}')
            sp, wi = {}, {}
            for dirn in ('pos', 'neg'):
                med = np.array([np.median(take(axn, dirn, c))
                                for c in cases])
                sp[dirn] = float(med.max() - med.min())
                wi[dirn] = float(np.median([iqr(take(axn, dirn, c))
                                            for c in cases]))
            fh.write('\\addlinespace[1pt]\n'
                     'case-median spread / med.\\ IQR & '
                     f'${sp["pos"]:.0f}$ / ${wi["pos"]:.0f}$ & '
                     f'${sp["neg"]:.0f}$ / ${wi["neg"]:.0f}$ & '
                     '-- & --\\\\\n')
            print(f'     spread/IQR  pos {sp["pos"]:.0f}/{wi["pos"]:.0f}'
                  f'  neg {sp["neg"]:.0f}/{wi["neg"]:.0f}\n')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
