#!/usr/bin/env python3
"""Campaign summary of the static-threshold residual per GE treatment.

Collapses the twenty per-group rows into one line per ground-effect
treatment: the median, RMS and empirical 95% interval (2.5th--97.5th
percentiles) of the run-level residual magnitude
|M_crit,est - M_crit,th| over the valid hardware runs. Reads
mcrit_per_run.csv (analysis/mcrit_prediction.py); emits
docs/tab_mcrit_residual_summary.tex.

Usage
-----
  python analysis/mcrit_residual_summary_table.py
         <scratch>/mcrit_per_run.csv [--outdir DIR]
"""
import argparse
import csv
from pathlib import Path

import numpy as np

TREAT = (('resid_none_mNm', 'No ground effect'),
         ('resid_single_mNm', 'Single rotor'),
         ('resid_interf_mNm', 'Rotor interference'))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('csv', type=Path)
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows = list(csv.DictReader(open(args.csv)))
    out = args.outdir / 'tab_mcrit_residual_summary.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Campaign summary of the run-level static-threshold\n'
            '% residual magnitude per ground-effect treatment.\n'
            '% Generated by analysis/mcrit_residual_summary_table.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Run-level residual magnitude\n'
            '$|M_{\\mathrm{crit,est}} - M_{\\mathrm{crit,th}}|$ of the\n'
            'identified critical moments against the static thresholds\n'
            f'under the three ground-effect treatments ({len(rows)}\n'
            'hardware runs): median, RMS and empirical 95\\% interval.}\n'
            '\\label{tab:mcrit_residual_summary}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}lccc@{}}\n\\toprule\n'
            ' & \\multicolumn{3}{c}{$|M_{\\mathrm{crit,est}} - '
            'M_{\\mathrm{crit,th}}|$ [mN$\\cdot$m]}\\\\\n'
            '\\cmidrule(l){2-4}\n'
            'Ground effect & median & RMS & 95\\% interval\\\\\n'
            '\\midrule\n')
        for col, lab in TREAT:
            v = np.array([float(r[col]) for r in rows])
            a = np.abs(v)
            lo, hi = np.percentile(a, [2.5, 97.5])
            fh.write(f'{lab} & ${np.median(a):.0f}$ & '
                     f'${np.sqrt(np.mean(v ** 2)):.0f}$ & '
                     f'$[{lo:.0f},\\,{hi:.0f}]$\\\\\n')
            print(f'{lab:20s} median {np.median(a):6.1f}  RMS '
                  f'{np.sqrt(np.mean(v ** 2)):6.1f}  '
                  f'[{lo:.1f}, {hi:.1f}] mN·m')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
