#!/usr/bin/env python3
"""Per-case CoM-offset error of the six detectors, load-cell truth.

For every hardware case and detector: the radial error
||p_off,est - p_off,true|| of the delivered estimate (pair average of
the directional group means, x from pitch and y from roll), with the
campaign RMS in the bottom row. Reads nls_comparison_runs.csv;
emits docs/tab_offset_error.tex.

Usage
-----
  python analysis/offset_error_table.py <scratch> [--outdir DIR]
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats

G = 9.81
MASS = {'case_01': 3.066, 'case_02': 3.220, 'case_03': 3.220,
        'case_04': 3.220, 'case_05': 3.220}
TRUTH = {('case_01', 'Mx'): -2.90, ('case_01', 'My'): -11.45,
         ('case_02', 'Mx'): -14.29, ('case_02', 'My'): -9.90,
         ('case_03', 'Mx'): -5.26, ('case_03', 'My'): 3.14,
         ('case_04', 'Mx'): 6.67, ('case_04', 'My'): 2.40,
         ('case_05', 'Mx'): 10.91, ('case_05', 'My'): -10.89}
SIGN = {'Mx': 1.0, 'My': -1.0}
METHODS = [('cosh', 'COSH'), ('cosh_cad', 'COSH-CAD'), ('nls', 'PNLS'),
           ('pelt_normal', 'CPD-N'), ('pelt_rbf', 'CPD-R'),
           ('cusum', 'CUSUM')]
CASES = [f'case_0{i}' for i in range(1, 6)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scratch', nargs='?', default='.',
                    help='directory holding nls_comparison_runs.csv')
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows = list(csv.DictReader(
        open(Path(args.scratch) / 'nls_comparison_runs.csv')))
    agg = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for r in rows:
        for m, _ in METHODS:
            if r.get(f'mcrit_{m}'):
                agg[(r['case'], r['axis'])][m][r['dir']].append(
                    float(r[f'mcrit_{m}']))

    def comp_err(case, axname, m):
        """Component error of the mean estimate and its Welch-t 95%
        half-width, from the two directional run groups."""
        g = agg[(case, axname)][m]
        W = MASS[case] * G
        s = 1e3 / W
        p, n = np.array(g['pos']), np.array(g['neg'])
        err = SIGN[axname] * s * 0.5 * (p.mean() + n.mean()) \
            - TRUTH[(case, axname)]
        var = .25 * (p.var(ddof=1) / len(p) + n.var(ddof=1) / len(n))
        num = (p.var(ddof=1) / len(p) + n.var(ddof=1) / len(n)) ** 2
        den = ((p.var(ddof=1) / len(p)) ** 2 / (len(p) - 1)
               + (n.var(ddof=1) / len(n)) ** 2 / (len(n) - 1))
        half = stats.t.ppf(.975, num / den) * s * np.sqrt(var)
        return err, half

    radial, halves = {}, {}
    for c in CASES:
        for m, _ in METHODS:
            ex, hx = comp_err(c, 'My', m)
            ey, hy = comp_err(c, 'Mx', m)
            radial[(c, m)] = float(np.hypot(ex, ey))
            halves[(c, m)] = float(np.hypot(hx, hy))

    out = args.outdir / 'tab_offset_error.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Radial CoM-offset error of the delivered estimate per\n'
            '% case and detector, against the load-cell truth.\n'
            '% Generated by analysis/offset_error_table.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Radial CoM-offset error\n'
            '$\\|p_{\\mathrm{off,est}} - p_{\\mathrm{off,true}}\\|$\n'
            '[mm] of the delivered estimate per case and detector,\n'
            'against the load-cell truth, with the 95\\% confidence\n'
            'half-width of the mean estimate (Welch-t per component,\n'
            'combined in quadrature); the bottom row is the RMS over\n'
            'the five cases.}\n'
            '\\label{tab:offset_error}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}l' + 'c' * len(METHODS) + '@{}}\n'
            '\\toprule\n'
            'Case & ' + ' & '.join(lab for _, lab in METHODS)
            + '\\\\\n\\midrule\n')
        for i, c in enumerate(CASES):
            cells = ' & '.join(
                f'${radial[(c, m)]:.2f} \\pm {halves[(c, m)]:.2f}$'
                for m, _ in METHODS)
            fh.write(f'E{i + 1} & {cells}\\\\\n')
            print(f'E{i + 1}: ' + '  '.join(
                f'{lab} {radial[(c, m)]:.2f}+-{halves[(c, m)]:.2f}'
                for m, lab in METHODS))
        comps = {m: np.array([comp_err(c, a, m)[0] for c in CASES
                              for a in ('My', 'Mx')])
                 for m, _ in METHODS}
        fh.write('\\midrule\n')

        def srow(name, fn, fmt='{:.2f}'):
            cells, txt = [], []
            for m, lab in METHODS:
                v = fn(m)
                cells.append(v if isinstance(v, str)
                             else f'${fmt.format(v)}$')
                txt.append(f'{lab} '
                           + (v if isinstance(v, str)
                              else fmt.format(v)))
            fh.write(f'{name} & ' + ' & '.join(cells) + '\\\\\n')
            print(f'{name}: ' + '  '.join(txt))

        def rms_norm(m):
            v = np.array([radial[(c, m)] for c in CASES])
            lo, hi = np.percentile(v, [2.5, 97.5])
            return (f'${np.sqrt(np.mean(v ** 2)):.2f}$ '
                    f'$[{lo:.2f},\\,{hi:.2f}]$')

        srow('RMS $\\|\\cdot\\|$ [95\\% int.]', rms_norm)
        srow('RMS (comp.)',
             lambda m: float(np.sqrt(np.mean(comps[m] ** 2))))
        srow('max $|\\cdot|$ (comp.)',
             lambda m: float(np.max(np.abs(comps[m]))))
        srow('mean (comp.)', lambda m: float(np.mean(comps[m])),
             fmt='{:+.2f}')
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
