#!/usr/bin/env python3
"""Per-case CoM-offset error of the six detectors, load-cell truth.

For every hardware case and detector: the radial error
||p_off,est - p_off,true|| of the delivered estimate (pair average of
the directional group means, x from pitch and y from roll), with the
campaign RMS in the bottom row. Reads nls_comparison_runs.csv;
emits docs/tab_offset_error.tex.

Usage
-----
  python analysis/offset_error_table.py <scratch> [--outdir DIR]
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

G = 9.81
MASS = {'case_01': 3.066, 'case_02': 3.220, 'case_03': 3.220,
        'case_04': 3.220, 'case_05': 3.220}
TRUTH = {('case_01', 'Mx'): -2.90, ('case_01', 'My'): -11.45,
         ('case_02', 'Mx'): -14.29, ('case_02', 'My'): -9.90,
         ('case_03', 'Mx'): -5.26, ('case_03', 'My'): 3.14,
         ('case_04', 'Mx'): 6.67, ('case_04', 'My'): 2.40,
         ('case_05', 'Mx'): 10.91, ('case_05', 'My'): -10.89}
SIGN = {'Mx': 1.0, 'My': -1.0}
METHODS = [('cosh', 'COSH'), ('cosh_cad', 'COSH-CAD'), ('nls', 'PNLS'),
           ('pelt_normal', 'CPD-N'), ('pelt_rbf', 'CPD-R'),
           ('cusum', 'CUSUM')]
CASES = [f'case_0{i}' for i in range(1, 6)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scratch', nargs='?', default='.',
                    help='directory holding nls_comparison_runs.csv')
    ap.add_argument('--outdir', type=Path, default=Path('docs'))
    args = ap.parse_args()

    rows = list(csv.DictReader(
        open(Path(args.scratch) / 'nls_comparison_runs.csv')))
    agg = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for r in rows:
        for m, _ in METHODS:
            if r.get(f'mcrit_{m}'):
                agg[(r['case'], r['axis'])][m][r['dir']].append(
                    float(r[f'mcrit_{m}']))

    def comp_err(case, axname, m):
        g = agg[(case, axname)][m]
        W = MASS[case] * G
        mff = 0.5 * (np.mean(g['pos']) + np.mean(g['neg']))
        return SIGN[axname] * 1e3 * mff / W - TRUTH[(case, axname)]

    radial = {(c, m): float(np.hypot(comp_err(c, 'My', m),
                                     comp_err(c, 'Mx', m)))
              for c in CASES for m, _ in METHODS}

    out = args.outdir / 'tab_offset_error.tex'
    with open(out, 'w') as fh:
        fh.write(
            '% Radial CoM-offset error of the delivered estimate per\n'
            '% case and detector, against the load-cell truth.\n'
            '% Generated by analysis/offset_error_table.py.\n'
            '\\begin{table}[t]\n'
            '\\caption{Radial CoM-offset error\n'
            '$\\|p_{\\mathrm{off,est}} - p_{\\mathrm{off,true}}\\|$\n'
            '[mm] of the delivered estimate per case and detector,\n'
            'against the load-cell truth; the bottom row is the RMS\n'
            'over the five cases.}\n'
            '\\label{tab:offset_error}\n'
            '\\centering\\small\n'
            '\\begin{tabular}{@{}l' + 'c' * len(METHODS) + '@{}}\n'
            '\\toprule\n'
            'Case & ' + ' & '.join(lab for _, lab in METHODS)
            + '\\\\\n\\midrule\n')
        for i, c in enumerate(CASES):
            cells = ' & '.join(f'${radial[(c, m)]:.2f}$'
                               for m, _ in METHODS)
            fh.write(f'E{i + 1} & {cells}\\\\\n')
            print(f'E{i + 1}: ' + '  '.join(
                f'{lab} {radial[(c, m)]:.2f}' for m, lab in METHODS))
        fh.write('\\midrule\nRMS & ' + ' & '.join(
            f'${np.sqrt(np.mean([radial[(c, m)] ** 2 for c in CASES])):.2f}$'
            for m, _ in METHODS) + '\\\\\n')
        print('RMS: ' + '  '.join(
            f'{lab} '
            f'{np.sqrt(np.mean([radial[(c, m)] ** 2 for c in CASES])):.2f}'
            for m, lab in METHODS))
        fh.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    print(f'written to {out}')


if __name__ == '__main__':
    main()
